baseURL = "https://matrixservers.net"
languageCode = "en-us"
title = "Matrix Servers"
shorttitle = "Matrix Servers"
theme = "matrix"
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
post = "/:title/"

[imaging]
quality = 68

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 3600
[caches.getcsv]
dir = ":cacheDir/:project"
maxAge = 3600
[caches.images]
dir = ":resourceDir/_gen"
maxAge = 3600
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = 3600

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Servers"
  url = "/servers"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3
[[menu.main]]
  name = "Add Server"
  url = "https://github.com/Atreatis/matrixservers"
  weight = 4
